## Sequential Way


In [1]:
import torch
import torch.nn as nn

In [4]:
seq=nn.Sequential(
    nn.Linear(10,5),
    nn.ReLU(),
    nn.Linear(5,15),
    nn.ReLU(),
    nn.Linear(15,2),
)

In [6]:
x=torch.rand(20,10)

In [7]:
neural=seq(x)

In [8]:
print(neural)

tensor([[-0.4277,  0.1740],
        [-0.3487,  0.1456],
        [-0.3389,  0.1454],
        [-0.3541,  0.1562],
        [-0.3493,  0.1590],
        [-0.3479,  0.1385],
        [-0.4089,  0.1634],
        [-0.3438,  0.1381],
        [-0.4076,  0.1707],
        [-0.3616,  0.1610],
        [-0.4100,  0.1777],
        [-0.4114,  0.1781],
        [-0.4000,  0.1583],
        [-0.3838,  0.1626],
        [-0.4126,  0.1534],
        [-0.3942,  0.1726],
        [-0.4319,  0.1753],
        [-0.3675,  0.1625],
        [-0.3755,  0.1394],
        [-0.3616,  0.1506]], grad_fn=<AddmmBackward0>)


In [10]:
seq[0].weight.data

tensor([[-0.0793, -0.1717,  0.2236,  0.2691,  0.2741, -0.0717, -0.0623,  0.1320,
          0.3135,  0.0403],
        [ 0.2780, -0.2615, -0.1140, -0.0657,  0.0718,  0.1183, -0.2080,  0.1947,
         -0.1088,  0.0099],
        [ 0.1363,  0.2697, -0.1058, -0.2087,  0.0162, -0.1090, -0.1541,  0.0386,
         -0.0264, -0.1201],
        [ 0.0428, -0.0805, -0.2640, -0.0731,  0.0355,  0.1148,  0.0101,  0.1790,
         -0.3023, -0.2122],
        [-0.2580, -0.1580,  0.2025, -0.1275, -0.0079,  0.2648,  0.2773, -0.2274,
         -0.0944, -0.1350]])

In [11]:
seq[0].bias.data

tensor([-0.2820, -0.2628, -0.1666, -0.0025,  0.2894])