In [81]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
import torch.optim as optim
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [82]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [83]:
iris=load_iris()

In [84]:
X=iris.data
y=iris.target

In [85]:
print(y.shape)
print(y)

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [86]:
ss=StandardScaler()
X=ss.fit_transform(X)

In [87]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [88]:
# converting number to tensor
X=torch.tensor(x,dtype=torch.float32).to(device)
y=torch.tensor(y,dtype=torch.long).to(device)

/tmp/ipykernel_13887/3129329828.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X=torch.tensor(x,dtype=torch.float32).to(device)


In [89]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

torch.Size([120, 4])
torch.Size([30, 4])
torch.Size([120])
torch.Size([30])


## Sequential way

In [90]:
print(x_train)

tensor([[ 1.2803e+00,  9.8217e-02,  7.6276e-01,  1.4488e+00],
        [-1.0218e+00, -1.7434e+00, -2.6032e-01, -2.6239e-01],
        [-5.3718e-01,  1.9398e+00, -1.3971e+00, -1.0522e+00],
        [ 1.0380e+00,  5.5861e-01,  1.1038e+00,  1.7121e+00],
        [ 1.2803e+00,  9.8217e-02,  6.4908e-01,  3.9577e-01],
        [ 1.0380e+00, -1.2830e+00,  1.1606e+00,  7.9067e-01],
        [-1.7367e-01, -5.9237e-01,  1.9438e-01,  1.3251e-01],
        [-5.3718e-01,  7.8881e-01, -1.2834e+00, -1.0522e+00],
        [-1.7367e-01, -5.9237e-01,  4.2173e-01,  1.3251e-01],
        [ 1.8983e-01, -3.6218e-01,  4.2173e-01,  3.9577e-01],
        [ 1.0380e+00,  9.8217e-02,  5.3541e-01,  3.9577e-01],
        [ 6.7450e-01,  9.8217e-02,  9.9011e-01,  7.9067e-01],
        [-1.0218e+00,  5.5861e-01, -1.3402e+00, -1.3154e+00],
        [ 3.1100e-01, -5.9237e-01,  1.3755e-01,  1.3251e-01],
        [ 7.9567e-01, -1.3198e-01,  8.1960e-01,  1.0539e+00],
        [ 1.1592e+00, -5.9237e-01,  5.9225e-01,  2.6414e-01],
        

In [91]:
s_model=nn.Sequential(
    nn.Linear(4,32),
    nn.ReLU(),
    nn.Linear(32,64),
    nn.ReLU(),
    nn.Linear(64,3),
)

In [92]:
s_model = s_model.to(device)  

In [96]:
s_m=s_model(x_train)
print(s_m)

tensor([[-0.0173,  0.1795, -0.0888],
        [ 0.0140,  0.0260, -0.1610],
        [ 0.1109,  0.1163, -0.1914],
        [ 0.0125,  0.1530, -0.0723],
        [ 0.0360,  0.1566, -0.1308],
        [-0.0928,  0.1679, -0.2720],
        [ 0.0057,  0.0485, -0.1217],
        [ 0.0671,  0.0479, -0.2054],
        [ 0.0064,  0.0504, -0.1272],
        [ 0.0098,  0.0757, -0.1043],
        [ 0.0360,  0.1407, -0.1092],
        [ 0.0264,  0.1299, -0.1254],
        [ 0.0584,  0.0173, -0.2318],
        [-0.0004,  0.0796, -0.1188],
        [-0.0120,  0.1486, -0.1169],
        [-0.0027,  0.1407, -0.2064],
        [ 0.0423,  0.2051, -0.1321],
        [ 0.0596,  0.0247, -0.2374],
        [-0.0474,  0.1103, -0.1430],
        [ 0.0867,  0.0547, -0.2223],
        [ 0.0850,  0.0322, -0.2513],
        [ 0.0046,  0.1787, -0.1087],
        [ 0.0735,  0.0382, -0.2171],
        [ 0.0401,  0.1141, -0.0604],
        [ 0.0588,  0.0302, -0.2252],
        [-0.0438,  0.0967, -0.1495],
        [-0.0549,  0.1562, -0.1551],
 

### Functional WAY

In [100]:
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.fl1=nn.Linear(4,32)
        self.fl2=nn.Linear(32,64)
        self.fl3=nn.Linear(64,3)
        self.relu=nn.ReLU()
    
    def forward(self,x):
        x=self.relu(self.fl1(x))   
        x=self.relu(self.fl2(x))   
        x=self.fl3(x)
    
        return x        

In [103]:
model=Model().to(device)

In [105]:
y_pred=model(x_train)
print(y_pred)

tensor([[ 1.7615e-02, -1.3431e-01, -1.4254e-01],
        [ 1.9754e-01, -1.0238e-01, -1.7617e-01],
        [ 4.4643e-02, -1.0136e-02, -1.5886e-01],
        [ 3.2313e-02, -1.3675e-01, -1.3219e-01],
        [ 2.6616e-03, -8.6359e-02, -1.8877e-01],
        [-2.0315e-02, -1.8021e-01, -1.6591e-01],
        [ 6.0090e-02, -1.1350e-01, -1.0726e-01],
        [ 1.4390e-01, -6.7059e-02, -2.0496e-01],
        [ 5.3404e-02, -1.0796e-01, -9.7348e-02],
        [ 3.6629e-02, -1.1201e-01, -8.9792e-02],
        [ 1.5326e-02, -9.1760e-02, -1.7184e-01],
        [ 2.0467e-02, -1.0666e-01, -1.1788e-01],
        [ 1.4578e-01, -7.1196e-02, -2.1277e-01],
        [ 6.8787e-02, -1.2221e-01, -1.2849e-01],
        [ 9.3820e-03, -1.3594e-01, -1.1755e-01],
        [ 2.6511e-02, -1.3195e-01, -1.7369e-01],
        [-3.5592e-02, -7.4153e-02, -1.9049e-01],
        [ 1.0465e-01, -7.0126e-02, -1.9229e-01],
        [ 4.7757e-03, -1.0475e-01, -9.2722e-02],
        [ 9.8828e-02, -4.9208e-02, -1.8347e-01],
        [ 8.4312e-02

In [114]:
criterion = nn.CrossEntropyLoss() 
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [115]:
num_epochs = 100  
batch_size = 16

In [116]:
def train_model(X_train, y_train):
    model.train()
    for epoch in range(num_epochs):
        
        outputs = model(X_train)
        loss = criterion(outputs, y_train)

     
        optimizer.zero_grad()
        loss.backward() 
        optimizer.step() 

        if (epoch + 1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
            
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

In [117]:
train_model(x_train,y_train)

Epoch [10/100], Loss: 0.9579
Epoch [10/100], Loss: 0.9579
Epoch [20/100], Loss: 0.8213
Epoch [20/100], Loss: 0.8213
Epoch [30/100], Loss: 0.6943
Epoch [30/100], Loss: 0.6943
Epoch [40/100], Loss: 0.5830
Epoch [40/100], Loss: 0.5830
Epoch [50/100], Loss: 0.4890
Epoch [50/100], Loss: 0.4890
Epoch [60/100], Loss: 0.4115
Epoch [60/100], Loss: 0.4115
Epoch [70/100], Loss: 0.3483
Epoch [70/100], Loss: 0.3483
Epoch [80/100], Loss: 0.2951
Epoch [80/100], Loss: 0.2951
Epoch [90/100], Loss: 0.2485
Epoch [90/100], Loss: 0.2485
Epoch [100/100], Loss: 0.2080
Epoch [100/100], Loss: 0.2080


In [ ]:
with torch.no_grad():  
    test_outputs = model(x_test)
    _, predicted = torch.max(test_outputs, 1)  
    accuracy = (predicted == y_test).sum().item() / y_test.size(0)
    print(f'Accuracy on the test set: {accuracy * 100:.2f}%')

Accuracy on the test set: 96.67%
